CheckExternal: false           # не пингаем внешние ссылки
DirectoryURLScheme: "file"     # для Antora-style «index.html ⇒ /»
CheckInternalHash: true
IgnoreInternalEmptyHash: true
IgnoreDirectoryMissingTrailingSlash: true
