[build]
  command = "make build"
  publish = "build/site"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = "make build"

[context.branch-deploy]
  command = "make build"
